name: Deploy Go Binary to Remote VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24 # Specify the Go version you need

      - name: Build Go Binary
        run: go build -o when-eat

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "$REMOTE_VM_IP" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_VM_IP: ${{ secrets.REMOTE_VM_IP }}

      - name: Stop Systemd Service
        run: |
          ssh -i ~/.ssh/id_rsa "$SSH_USER"@"$REMOTE_VM_IP" 'systemctl --user stop when-eat'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_VM_IP: ${{ secrets.REMOTE_VM_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}

      - name: Copy whole dir to VM lol
        run: |
          scp -i ~/.ssh/id_rsa -r * "$SSH_USER"@"$REMOTE_VM_IP":/opt/when-eat
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_VM_IP: ${{ secrets.REMOTE_VM_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}

      - name: Restart Systemd Service
        run: |
          ssh -i ~/.ssh/id_rsa "$SSH_USER"@"$REMOTE_VM_IP" 'systemctl --user restart when-eat'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_VM_IP: ${{ secrets.REMOTE_VM_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
